@startuml
title "Теплый дом" Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "Клиент", "Клиент системы Теплый дом")
Person(admin, "Инженер", "Инженер системы Теплый дом")
System(warmHouseSystem, "Система Умный дом", "Система управления")

System_Ext(devices, "Устройства", "Устройства управляющие отопительным оборудованием")
System_Ext(sensors, "Sensors", "Датчики")

Rel(client, warmHouseSystem, "Управляет отоплением, мониторит температуру")
Rel(warmHouseSystem,devices,"Изменяет температуру")
Rel(warmHouseSystem,sensors,"Получает данные о температуре")
Rel(admin,devices,"Устанавливает и регистрирует оборудование")
Rel(admin,sensors,"Устанавливает и регистрирует датчики")


@enduml